/**
 * Layout component for the application.
 * This component defines the basic layout structure of the application, including the header, footer, and global styles.
 * It also sets metadata such as the title and description of the page.
 * @param {React.ReactNode} children The child components to be rendered within the layout.
 * @returns {ReactElement} The root layout of the application.
 */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chuck Norris quotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
